# Generated by Django 5.1.2 on 2024-10-16 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=85)),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
                'db_table': 'eco_ext_departamento',
            },
        ),
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id_eps', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_eps', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Eps',
                'db_table': 'eco_bas_eps',
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id_ecivil', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_ecivil', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Estado civil',
                'db_table': 'eco_bas_estadocivil',
            },
        ),
        migrations.CreateModel(
            name='FondoPensiones',
            fields=[
                ('id_fpensiones', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_fpensiones', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Fondo de pensiones',
                'db_table': 'eco_bas_fpensiones',
            },
        ),
        migrations.CreateModel(
            name='GpRh',
            fields=[
                ('id_grh', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_grh', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Grupo rh',
                'db_table': 'eco_bas_gruporh',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=170)),
                ('es_colombia', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Países',
                'db_table': 'eco_ext_pais',
            },
        ),
        migrations.CreateModel(
            name='TipoGenero',
            fields=[
                ('id_tgenero', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_tgenero', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Tipo de género',
                'db_table': 'eco_bas_tipogenero',
            },
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id_tidentificacion', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_tidentificacion', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Tipo de identificación',
                'db_table': 'eco_bas_tipoidentificacion',
            },
        ),
        migrations.CreateModel(
            name='ZonaUbicacion',
            fields=[
                ('id_zubicacion', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_zubicacion', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Zona de ubicación',
                'db_table': 'eco_bas_zonaubicacion',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_municipio', models.CharField(max_length=85)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.departamento')),
            ],
            options={
                'verbose_name_plural': 'Municipios',
                'db_table': 'eco_ext_municipio',
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.pais'),
        ),
    ]
